-- =============================================
-- Existing tables (matching production Supabase schema)
-- =============================================

-- AI agent instructions per category (read by both n8n and AI Engine)
CREATE TABLE ai_answerer_instructions (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    type TEXT,
    name TEXT NOT NULL,
    instruction_1 TEXT,
    instruction_2 TEXT,
    instruction_3 TEXT,
    instruction_4 TEXT,
    instruction_5 TEXT,
    instruction_6 TEXT,
    instruction_7 TEXT,
    instruction_8 TEXT,
    instruction_9 TEXT,
    instruction_10 TEXT,
    description TEXT DEFAULT '',
    version TEXT DEFAULT 'v3',
    status TEXT NOT NULL DEFAULT 'enabled',
    staging TEXT DEFAULT 'production',
    outstanding_rules TEXT,
    outstanding_examples TEXT,
    outstanding_hard_rules TEXT,
    auto_send_enabled BOOLEAN DEFAULT false
);

CREATE INDEX idx_instructions_name ON ai_answerer_instructions(name);
CREATE INDEX idx_instructions_status ON ai_answerer_instructions(status);
CREATE INDEX idx_instructions_type ON ai_answerer_instructions(type);

-- Customer support threads (existing n8n pipeline data — production schema)
CREATE TABLE support_threads_data (
    thread_id VARCHAR NOT NULL,
    ticket_id VARCHAR NOT NULL,
    request_type VARCHAR,
    requires_reply BOOLEAN,
    requires_identification BOOLEAN,
    requires_editing BOOLEAN,
    requires_subscription_info BOOLEAN,
    requires_tracking_info BOOLEAN,
    requires_box_contents_info BOOLEAN,
    "user" TEXT,
    status VARCHAR,
    identification TEXT,
    subscription_info TEXT,
    tracking_info TEXT,
    box_contents_info TEXT,
    ai_draft_reply TEXT,
    full_request TEXT,
    request_subtype VARCHAR,
    prompt_version TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    thread_date TIMESTAMPTZ,
    request_sub_subtype TEXT,
    action_analysis TEXT,
    CONSTRAINT support_threads_data_pkey PRIMARY KEY (thread_id)
);

CREATE INDEX idx_support_threads_ticket_identification ON support_threads_data(ticket_id) WHERE identification IS NOT NULL;
CREATE INDEX idx_support_threads_thread_date ON support_threads_data(thread_date DESC);
CREATE INDEX idx_support_threads_date_status_type ON support_threads_data(created_at DESC, status, request_type);
CREATE INDEX idx_support_threads_created_at ON support_threads_data(created_at DESC);
CREATE INDEX idx_support_threads_request_type ON support_threads_data(request_type);
CREATE INDEX idx_support_threads_prompt_version ON support_threads_data(prompt_version);
CREATE INDEX idx_support_threads_date_status ON support_threads_data(created_at DESC, status);
CREATE INDEX idx_support_threads_requires_reply ON support_threads_data(requires_reply);
CREATE INDEX idx_support_threads_data_ticket_id ON support_threads_data(ticket_id);
CREATE INDEX idx_support_threads_data_status ON support_threads_data(status);
CREATE INDEX idx_support_threads_data_status_subtype ON support_threads_data(status, request_subtype);

-- AI agent tasks (existing n8n pipeline)
CREATE TABLE ai_agent_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255) NOT NULL,
    request TEXT,
    response TEXT,
    status VARCHAR(255) NOT NULL,
    ticket_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    thread_id VARCHAR(255),
    CONSTRAINT ai_agent_tasks_pkey PRIMARY KEY (id)
);

CREATE INDEX ai_agent_tasks_type_index ON ai_agent_tasks(type);
CREATE INDEX ai_agent_tasks_status_index ON ai_agent_tasks(status);
CREATE INDEX ai_agent_tasks_ticket_id_index ON ai_agent_tasks(ticket_id);
CREATE INDEX ai_agent_tasks_thread_id_index ON ai_agent_tasks(thread_id);

-- AI vs Human comparison (existing n8n pipeline)
CREATE TABLE ai_human_comparison (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT,
    thread_id TEXT,
    full_request TEXT,
    subscription_info JSONB,
    tracking_info JSONB,
    human_reply TEXT,
    ai_reply TEXT,
    ai_reply_date TIMESTAMPTZ,
    human_reply_date TIMESTAMPTZ,
    comment TEXT,
    request_subtype TEXT,
    email TEXT,
    changes JSONB,
    updated_at TIMESTAMPTZ,
    ticket_id TEXT,
    human_reply_original TEXT,
    check_count BIGINT,
    changed BOOLEAN DEFAULT false,
    last_checked_at TIMESTAMPTZ,
    improvement_suggestions JSONB,
    similarity_score BIGINT,
    prompt_version TEXT,
    change_classification TEXT,
    root_cause TEXT,
    draft_update_count INTEGER DEFAULT 0,
    is_outstanding BOOLEAN DEFAULT false,
    request_sub_subtype TEXT,
    CONSTRAINT ai_human_comparison_pkey PRIMARY KEY (id),
    CONSTRAINT unique_thread_id UNIQUE (thread_id),
    CONSTRAINT similarity_score_range CHECK (similarity_score >= 0 AND similarity_score <= 100)
);

CREATE INDEX idx_ai_comparison_thread_id ON ai_human_comparison(thread_id);
CREATE INDEX idx_ai_comparison_classification ON ai_human_comparison(change_classification);
CREATE INDEX idx_ai_comparison_status ON ai_human_comparison(status);
CREATE INDEX idx_ai_comparison_changed ON ai_human_comparison(changed);
CREATE INDEX idx_ai_comparison_date_category ON ai_human_comparison(created_at DESC, request_subtype);
CREATE INDEX idx_ai_human_prompt_version ON ai_human_comparison(prompt_version);
CREATE INDEX idx_ai_human_created_at ON ai_human_comparison(created_at DESC);
CREATE INDEX idx_ai_human_request_subtype ON ai_human_comparison(request_subtype);
CREATE INDEX idx_ai_human_email ON ai_human_comparison(email);

-- Support dialogs (existing n8n pipeline — message history)
CREATE TABLE support_dialogs (
    id BIGSERIAL NOT NULL,
    thread_id VARCHAR(255) NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    ticket_id VARCHAR(255) NOT NULL,
    direction VARCHAR(255) NOT NULL,
    ticket_subject VARCHAR(255) NOT NULL,
    thread_summary VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    status TEXT DEFAULT 'new',
    data JSONB,
    CONSTRAINT support_dialogs_pkey PRIMARY KEY (id),
    CONSTRAINT support_dialogs_thread_id_unique UNIQUE (thread_id)
);

CREATE INDEX idx_support_dialogs_status_direction_date ON support_dialogs(status, direction, date DESC);
CREATE INDEX idx_support_dialogs_ticket_thread ON support_dialogs(ticket_id, thread_id DESC);
CREATE INDEX support_dialogs_ticket_id_index ON support_dialogs(ticket_id);
CREATE INDEX support_dialogs_direction_index ON support_dialogs(direction);
CREATE INDEX support_dialogs_email_index ON support_dialogs(email);
CREATE INDEX idx_support_dialogs_date ON support_dialogs(date DESC);

-- Eval results (existing n8n pipeline — production schema)
CREATE TABLE eval_results (
    id SERIAL NOT NULL,
    thread_id INTEGER,
    ticket_id TEXT,
    request_subtype TEXT,
    request_sub_subtype TEXT,
    decision TEXT NOT NULL,
    draft_reason TEXT,
    confidence TEXT,
    checks JSONB,
    overrides JSONB,
    is_outstanding BOOLEAN,
    outstanding_trigger TEXT,
    auto_send_enabled BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT eval_results_pkey PRIMARY KEY (id)
);

-- =============================================
-- New tables (AI Engine chat platform)
-- =============================================

-- Chat sessions
CREATE TABLE chat_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id TEXT UNIQUE NOT NULL,
    conversation_id TEXT,
    channel TEXT NOT NULL DEFAULT 'widget',
    customer_email TEXT,
    customer_name TEXT,
    customer_id TEXT,
    subscription_id TEXT,
    primary_category TEXT,
    secondary_category TEXT,
    urgency TEXT DEFAULT 'medium',
    language TEXT DEFAULT 'en',
    status TEXT NOT NULL DEFAULT 'active',
    assigned_to TEXT,
    escalation_reason TEXT,
    eval_decision TEXT,
    eval_confidence TEXT,
    is_outstanding BOOLEAN DEFAULT false,
    outstanding_trigger TEXT,
    first_response_time_ms INTEGER,
    total_messages INTEGER DEFAULT 0,
    ai_messages INTEGER DEFAULT 0,
    human_messages INTEGER DEFAULT 0,
    resolution_time_seconds INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    csat_score INTEGER,
    csat_comment TEXT
);

CREATE INDEX idx_chat_sessions_email ON chat_sessions(customer_email);
CREATE INDEX idx_chat_sessions_status ON chat_sessions(status);
CREATE INDEX idx_chat_sessions_category ON chat_sessions(primary_category);
CREATE INDEX idx_chat_sessions_created ON chat_sessions(created_at DESC);
CREATE INDEX idx_chat_sessions_conversation ON chat_sessions(conversation_id);

-- Chat messages
CREATE TABLE chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id TEXT NOT NULL REFERENCES chat_sessions(session_id),
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    model_used TEXT,
    reasoning_effort TEXT,
    tools_used JSONB DEFAULT '[]'::jsonb,
    processing_time_ms INTEGER,
    token_count INTEGER,
    cost_usd NUMERIC(10, 6),
    actions_taken JSONB DEFAULT '[]'::jsonb,
    actions_pending JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_messages_session ON chat_messages(session_id);
CREATE INDEX idx_chat_messages_created ON chat_messages(created_at);
CREATE INDEX idx_chat_messages_role ON chat_messages(role);

-- Agent traces
CREATE TABLE agent_traces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id TEXT NOT NULL REFERENCES chat_sessions(session_id),
    message_id UUID REFERENCES chat_messages(id),
    step TEXT NOT NULL,
    agent_name TEXT NOT NULL,
    input_data JSONB,
    output_data JSONB,
    model TEXT,
    reasoning_effort TEXT,
    tokens_input INTEGER,
    tokens_output INTEGER,
    cost_usd NUMERIC(10, 6),
    duration_ms INTEGER,
    status TEXT NOT NULL DEFAULT 'success',
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_traces_session ON agent_traces(session_id);
CREATE INDEX idx_agent_traces_step ON agent_traces(step);
CREATE INDEX idx_agent_traces_status ON agent_traces(status);
CREATE INDEX idx_agent_traces_created ON agent_traces(created_at DESC);

-- Tool executions
CREATE TABLE tool_executions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id TEXT NOT NULL REFERENCES chat_sessions(session_id),
    trace_id UUID REFERENCES agent_traces(id),
    tool_name TEXT NOT NULL,
    tool_input JSONB,
    tool_output JSONB,
    requires_approval BOOLEAN DEFAULT false,
    approval_status TEXT,
    approved_at TIMESTAMPTZ,
    approved_by TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    duration_ms INTEGER,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tool_executions_session ON tool_executions(session_id);
CREATE INDEX idx_tool_executions_tool ON tool_executions(tool_name);
CREATE INDEX idx_tool_executions_status ON tool_executions(status);
CREATE INDEX idx_tool_executions_approval ON tool_executions(approval_status) WHERE requires_approval = true;

-- Learning records
CREATE TABLE learning_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category TEXT,
    subcategory TEXT,
    agent_name TEXT NOT NULL,
    learning_type TEXT NOT NULL,
    trigger_description TEXT,
    learned_pattern TEXT NOT NULL,
    confidence NUMERIC(3, 2),
    times_applied INTEGER DEFAULT 0,
    success_rate NUMERIC(3, 2),
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_applied_at TIMESTAMPTZ
);

CREATE INDEX idx_learning_category ON learning_records(category);
CREATE INDEX idx_learning_status ON learning_records(status);

-- Human corrections of AI responses (Phase 9: correction learning pipeline)
CREATE TABLE correction_patterns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id TEXT,
    session_id TEXT,
    category TEXT NOT NULL,
    ai_response TEXT NOT NULL,
    human_edit TEXT NOT NULL,
    correction_type TEXT NOT NULL,  -- tone, accuracy, safety, completeness
    specific_issue TEXT,
    key_changes JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_correction_category ON correction_patterns(category, created_at DESC);

-- Instruction update suggestions (Phase 9: eval-driven learning)
CREATE TABLE instruction_updates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category TEXT NOT NULL,
    issue_pattern TEXT NOT NULL,
    suggested_fix TEXT NOT NULL,
    supporting_examples JSONB DEFAULT '[]',
    frequency INTEGER DEFAULT 1,
    status TEXT DEFAULT 'pending',  -- pending, approved, rejected, deployed
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ
);

CREATE INDEX idx_instruction_updates_status ON instruction_updates(status, category);
